var mongoose = require('mongoose');
var Schema = mongoose.Schema;
//var passportLocalMongoose = require('passport-local-mongoose');

var Account = new Schema({
    user_id: {type: String, required: true, unique: true},
    username: {type: String, required: true, unique: true},
    password: {type: String, required: true},
    email: {type: String, required: true},
});

var Vote = new Schema({
    vote_id: {type: String, required: true, unique: true},
    vote_title: {type: String, required: true},
    publisher_id: {type: String, required: true},
    publish_time: {type: Date, dafault: Date.now},
    expire_time: {type: Date, dafault: Date.now},
    bar_fix_color: {type: String, default: '#36A2EB'},
    bar_add_color: {type: String, default: '#FF6384'},
    topic_title: {type: String},
    topic_content: {type: String},
    anonymous_publish: {type: Boolean, required:true},
    anonymous_ticket: {type: Boolean, required:true},
    anonymous_comment: {type: Boolean, required:true},
});

var VoteMenu = new Schema({
    vote_id: {type: String, required: true},
    ticket: {type: Number, default: 0},
    shoot: {type: Number, default: 0},
    quote: {type: Number, default: 0},
    watch: {type: Number, default: 0},
    comment: {type: Number, default: 0},
});

var VoteComment = new Schema({
    vote_id: {type: String, required: true},
    comment_id: {type: String, required: true},
    parent_id: {type: String},
    reply_id: {type: String},
    publisher_id: {type: String, required: true},
    publish_time: {type: Date, dafault: Date.now},
    content: {type: String, required: true},
    good: {type: Number, default: 0},
    bad: {type: Number, default: 0},
});

var VoteOption = new Schema({
    vote_id: {type: String, required: true},
    name_0: {type: String},
    count_0: {type: Number},
    name_1: {type: String},
    count_1: {type: Number},
    name_2: {type: String},
    count_2: {type: Number},
    name_3: {type: String},
    count_3: {type: Number},
    name_4: {type: String},
    count_4: {type: Number},
    name_5: {type: String},
    count_5: {type: Number},
    name_6: {type: String},
    count_6: {type: Number},
    name_7: {type: String},
    count_7: {type: Number},
    name_8: {type: String},
    count_8: {type: Number},
    name_8: {type: String},
    count_9: {type: Number},
    name_10: {type: String},
    count_10: {type: Number},
    name_11: {type: String},
    count_11: {type: Number},
    name_12: {type: String},
    count_12: {type: Number},
    name_13: {type: String},
    count_13: {type: Number},
    name_14: {type: String},
    count_14: {type: Number},
    name_15: {type: String},
    count_15: {type: Number},
    name_16: {type: String},
    count_16: {type: Number},
    name_17: {type: String},
    count_17: {type: Number},
    name_18: {type: String},
    count_18: {type: Number},
    name_19: {type: String},
    count_19: {type: Number},
    name_20: {type: String},
    count_20: {type: Number},
    name_21: {type: String},
    count_21: {type: Number},
    name_22: {type: String},
    count_22: {type: Number},
    name_23: {type: String},
    count_23: {type: Number},
    name_24: {type: String},
    count_24: {type: Number},
    name_25: {type: String},
    count_25: {type: Number},
    name_26: {type: String},
    count_26: {type: Number},
    name_27: {type: String},
    count_27: {type: Number},
    name_28: {type: String},
    count_28: {type: Number},
    name_29: {type: String},
    count_29: {type: Number},
    name_30: {type: String},
    count_30: {type: Number},
    name_31: {type: String},
    count_31: {type: Number},
    name_32: {type: String},
    count_32: {type: Number},
    name_33: {type: String},
    count_33: {type: Number},
    name_34: {type: String},
    count_34: {type: Number},
    name_35: {type: String},
    count_35: {type: Number},
    name_36: {type: String},
    count_36: {type: Number},
    name_37: {type: String},
    count_37: {type: Number},
    name_38: {type: String},
    count_38: {type: Number},
    name_39: {type: String},
    count_39: {type: Number},
    name_40: {type: String},
    count_40: {type: Number},
    name_41: {type: String},
    count_41: {type: Number},
    name_42: {type: String},
    count_42: {type: Number},
    name_43: {type: String},
    count_43: {type: Number},
    name_44: {type: String},
    count_44: {type: Number},
    name_45: {type: String},
    count_45: {type: Number},
    name_46: {type: String},
    count_46: {type: Number},
    name_47: {type: String},
    count_47: {type: Number},
    name_48: {type: String},
    count_48: {type: Number},
    name_49: {type: String},
    count_49: {type: Number},
});

//Account.plugin(passportLocalMongoose);

module.exports = {
  Account: mongoose.model('Account', Account),
  Vote: mongoose.model('Vote', Vote),
  VoteMenu: mongoose.model('VoteMenu', VoteMenu),
  VoteOption: mongoose.model('VoteOption', VoteOption),
  VoteComment: mongoose.model('VoteComment', VoteComment),
}
