var mongoose = require('mongoose');
var Schema = mongoose.Schema;
//var passportLocalMongoose = require('passport-local-mongoose');

var Account = new Schema({
    user_id: {type: String, required: true, unique: true},
    username: {type: String, required: true, unique: true},
    password: {type: String, required: true},
    email: {type: String, required: true},
});

var Vote = new Schema({
    vote_id: {type: String, required: true, unique: true},
    vote_title: {type: String, required: true},
    publisher_id: {type: String, required: true},
    publish_time: {type: Date, dafault: Date.now},
    expire_time: {type: Date, dafault: Date.now},
    chart_type: {type: String, required: true},
    topic_title: {type: String},
    topic_content: {type: String},
    anonymous_publish: {type: Boolean, required:true},
    anonymous_ticket: {type: Boolean, required:true},
    anonymous_comment: {type: Boolean, required:true},
});

var VoteMenu = new Schema({
    vote_id: {type: String, required: true},
    ticket: {type: Number, default: 0},
    shoot: {type: Number, default: 0},
    quote: {type: Number, default: 0},
    watch: {type: Number, default: 0},
    comment: {type: Number, default: 0},
});

var VoteComment = new Schema({
    vote_id: {type: String, required: true},
    comment_id: {type: String, required: true},
    parent_id: {type: String},
    publisher_id: {type: String, required: true},
    publish_time: {type: Date, dafault: Date.now},
    content: {type: String, required: true},
    good: {type: Number, default: 0},
    bad: {type: Number, default: 0},
});

var VoteOption = new Schema({
    vote_id: {type: String, required: true},
    sequence: {type: Array, default: []},
    name_0: {type: String},
    count_0: {type: Number},
    color_0: {type: Array},
    name_1: {type: String},
    count_1: {type: Number},
    color_1: {type: Array},
    name_2: {type: String},
    count_2: {type: Number},
    color_2: {type: Array},
    name_3: {type: String},
    count_3: {type: Number},
    color_3: {type: Array},
    name_4: {type: String},
    count_4: {type: Number},
    color_4: {type: Array},
    name_5: {type: String},
    count_5: {type: Number},
    color_5: {type: Array},
    name_6: {type: String},
    count_6: {type: Number},
    color_6: {type: Array},
    name_7: {type: String},
    count_7: {type: Number},
    color_7: {type: Array},
    name_8: {type: String},
    count_8: {type: Number},
    color_8: {type: Array},
    name_8: {type: String},
    count_9: {type: Number},
    color_9: {type: Array},
    name_10: {type: String},
    count_10: {type: Number},
    name_11: {type: String},
    count_11: {type: Number},
    name_12: {type: String},
    count_12: {type: Number},
    name_13: {type: String},
    count_13: {type: Number},
    name_14: {type: String},
    count_14: {type: Number},
    name_15: {type: String},
    count_15: {type: Number},
    name_16: {type: String},
    count_16: {type: Number},
    name_17: {type: String},
    count_17: {type: Number},
    name_18: {type: String},
    count_18: {type: Number},
    name_19: {type: String},
    count_19: {type: Number},
    name_20: {type: String},
    count_20: {type: Number},
    name_21: {type: String},
    count_21: {type: Number},
    name_22: {type: String},
    count_22: {type: Number},
    name_23: {type: String},
    count_23: {type: Number},
    name_24: {type: String},
    count_24: {type: Number},
    name_25: {type: String},
    count_25: {type: Number},
    name_26: {type: String},
    count_26: {type: Number},
    name_27: {type: String},
    count_27: {type: Number},
    name_28: {type: String},
    count_28: {type: Number},
    name_29: {type: String},
    count_29: {type: Number},
    name_30: {type: String},
    count_30: {type: Number},
    name_31: {type: String},
    count_31: {type: Number},
    name_32: {type: String},
    count_32: {type: Number},
    name_33: {type: String},
    count_33: {type: Number},
    name_34: {type: String},
    count_34: {type: Number},
    name_35: {type: String},
    count_35: {type: Number},
    name_36: {type: String},
    count_36: {type: Number},
    name_37: {type: String},
    count_37: {type: Number},
    name_38: {type: String},
    count_38: {type: Number},
    name_39: {type: String},
    count_39: {type: Number},
    name_40: {type: String},
    count_40: {type: Number},
    name_41: {type: String},
    count_41: {type: Number},
    name_42: {type: String},
    count_42: {type: Number},
    name_43: {type: String},
    count_43: {type: Number},
    name_44: {type: String},
    count_44: {type: Number},
    name_45: {type: String},
    count_45: {type: Number},
    name_46: {type: String},
    count_46: {type: Number},
    name_47: {type: String},
    count_47: {type: Number},
    name_48: {type: String},
    count_48: {type: Number},
    name_49: {type: String},
    count_49: {type: Number},
    name_50: {type: String},
    count_50: {type: Number},
    name_51: {type: String},
    count_51: {type: Number},
    name_52: {type: String},
    count_52: {type: Number},
    name_53: {type: String},
    count_53: {type: Number},
    name_54: {type: String},
    count_54: {type: Number},
    name_55: {type: String},
    count_55: {type: Number},
    name_56: {type: String},
    count_56: {type: Number},
    name_57: {type: String},
    count_57: {type: Number},
    name_58: {type: String},
    count_58: {type: Number},
    name_59: {type: String},
    count_59: {type: Number},
    name_60: {type: String},
    count_60: {type: Number},
    name_61: {type: String},
    count_61: {type: Number},
    name_62: {type: String},
    count_62: {type: Number},
    name_63: {type: String},
    count_63: {type: Number},
    name_64: {type: String},
    count_64: {type: Number},
    name_65: {type: String},
    count_65: {type: Number},
    name_66: {type: String},
    count_66: {type: Number},
    name_67: {type: String},
    count_67: {type: Number},
    name_68: {type: String},
    count_68: {type: Number},
    name_69: {type: String},
    count_69: {type: Number},
    name_70: {type: String},
    count_70: {type: Number},
    name_71: {type: String},
    count_71: {type: Number},
    name_72: {type: String},
    count_72: {type: Number},
    name_73: {type: String},
    count_73: {type: Number},
    name_74: {type: String},
    count_74: {type: Number},
    name_75: {type: String},
    count_75: {type: Number},
    name_76: {type: String},
    count_76: {type: Number},
    name_77: {type: String},
    count_77: {type: Number},
    name_78: {type: String},
    count_78: {type: Number},
    name_79: {type: String},
    count_79: {type: Number},
    name_80: {type: String},
    count_80: {type: Number},
    name_81: {type: String},
    count_81: {type: Number},
    name_82: {type: String},
    count_82: {type: Number},
    name_83: {type: String},
    count_83: {type: Number},
    name_84: {type: String},
    count_84: {type: Number},
    name_85: {type: String},
    count_85: {type: Number},
    name_86: {type: String},
    count_86: {type: Number},
    name_87: {type: String},
    count_87: {type: Number},
    name_88: {type: String},
    count_88: {type: Number},
    name_89: {type: String},
    count_89: {type: Number},
    name_90: {type: String},
    count_90: {type: Number},
    name_91: {type: String},
    count_91: {type: Number},
    name_92: {type: String},
    count_92: {type: Number},
    name_93: {type: String},
    count_93: {type: Number},
    name_94: {type: String},
    count_94: {type: Number},
    name_95: {type: String},
    count_95: {type: Number},
    name_96: {type: String},
    count_96: {type: Number},
    name_97: {type: String},
    count_97: {type: Number},
    name_98: {type: String},
    count_98: {type: Number},
    name_99: {type: String},
    count_99: {type: Number},
});

//Account.plugin(passportLocalMongoose);

module.exports = {
  Account: mongoose.model('Account', Account),
  Vote: mongoose.model('Vote', Vote),
  VoteMenu: mongoose.model('VoteMenu', VoteMenu),
  VoteOption: mongoose.model('VoteOption', VoteOption),
  VoteComment: mongoose.model('VoteComment', VoteComment),
}
